server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test-stream?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
